### ISSUE TITLE
Right ALT still not behaving properly for Polish keyboard layout

### ISSUE THREAD

**Issue by ludwiktrammer** [atom/atom-keymap#169]
Atom 1.12 made big improvements in the realms of international keyboard support. Unfortunately people using Polish keyboard layout still can not use two characters from the Polish alphabet: `ą` (`alt-a`) and `Ś` (`alt+shift+s`) .  It looks like `alt-a` binding is already taken by `project-find:show-in-current-directory` command and `alt-shift-s` is taken by `snippets:available`.

As for now the problem have been confirmed with Atom 1.12 on Mac OS X (Mac OS X 10.12.1 by szimek in #35  and Mac OS X 10.11.6 by me). 

There is a workaround described by @Ben3eeE - one can add following code to the init script:

```
atom.keymaps.addKeystrokeResolver ({event}) ->
  if event.code is 'KeyS' and event.altKey and event.shiftKey
    return 'Ś'
  if event.code is 'KeyA' and event.altKey
    return 'ą'
```

If I understand correctly 1.12 was supposed to fix such problems, so I'd guess this qualifies as a bug?

**Comment by Ben3eeE** [comment]
@nathansobo I forget how this is supposed to work on macOS. I know Windows should always favor the AltGraph variant.

**Comment by nathansobo** [comment]
Sorry about this. We had a couple default bindings that I actually decided to remove and then forgot. Somehow I didn't hear any complaints during the beta period and forgot to remove them. We'll have a hotfix out soon with these bindings removed.

**Comment by nathansobo** [comment]
Fixed via https://github.com/atom/find-and-replace/commit/f37f3d8dd9a657784cc9630d5c4f834181a18dc4 and https://github.com/atom/snippets/commit/690d4fd8ef9886fdace3c8cd511bf134bcde22d2.

Available now via 1.12.1. Thanks for the report!

**Comment by ilidan85** [comment]
I'm still having problem with ż (alt + z) and ó (alt + o) also Polish keyboard
Atom 1.12.5, Win 10

**Comment by Ben3eeE** [comment]
@ilidan85 for those keys and Atom 1.12 this is expected. The keys are bound to `editor:checkout-head-revision` and `application:add-project-folder`. These keybindings were only removed or moved in Atom 1.13 since they are more common.

So your solution is to either unset these keybindings in Atom 1.12 or to run Atom beta.  To unset the keybindings add the following to your `keymap.cson` which you can reach from the file menu. File -> Keymap...

```cson
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-z': 'unset!'
 
'body':
  'ctrl-alt-o': 'unset!'
```

**Comment by flagoon** [comment]
I tried to unset those keys, and after adding part of text to Keymap, they are highlighted in Keybidings as unset, but nothing changed. I still can't use alt+a (ą) alt+c (ć) and alt+o (ó). I'm using version 1.14.3.
