### ISSUE TITLE
[win 10] fold/unfold-all shortcut not working on Atom 1.12.2

### ISSUE THREAD

**Issue by flaviolaino** [atom/atom-keymap#176]
Before 1.12 to fold-all I used ctrl-shift-alt-' and to unfold-all I used ctrl-shift-alt-ì
After update to 1.12.2 those shortcut are converted in ctrl-alt-{ and ctrl-alt-} (or ctrl-k), but doesn't work.

Thanks

**Comment by nathansobo** [comment]
@flaviolaino Can you toggle the keystroke resolver via the command palette and take a screen shot of what you're seeing when you run the expected keystroke?

**Comment by eulogy14** [comment]
Same goes for me.. Every Ctrl-Alt-KEY used Alt-Gr version instead of atom predefined or keymap-defined functions.

For example, ctrl-alt-b was beautification, now it is writing { etc..

**Comment by flaviolaino** [comment]
Here the screenshot for ctrl-shit-alt-ì (ctrl-alt-^):
![image](https://cloud.githubusercontent.com/assets/10008037/20348647/d17e2f9a-ac06-11e6-8138-ad8b42f2cc04.png)
Same thing for ctrl-shit-alt-' (ctrl-alt-?)

**Comment by Ben3eeE** [comment]
@flaviolaino @eulogy14 What keyboard layouts are you using? Can you test the latest version of Atom 1.12.4? We made major changes to how Ctrl-Alt resolves in this version so this might have been fixed with that.

**Comment by flaviolaino** [comment]
My keyboard is QWERTY Italian.
Updating to 1.12.4 not resolve.

**Comment by eulogy14** [comment]
Hunggarian qwerty. Problem still persists after update :)

Flavio Laino <notifications@github.com> ezt írta (időpont: 2016. nov. 18.,
Pén 10:48):

**Comment by Ben3eeE** [comment]
@eulogy14 What do you see in the keybinding resolver when pressing <kbd>Ctrl-Alt-b</kbd>.

**Comment by eulogy14** [comment]
CTRL-ALT and when i press "b" it turns to {

Linus Eriksson <notifications@github.com> ezt írta (időpont: 2016. nov.
18., P, 11:01):

**Comment by flaviolaino** [comment]
ctrl-alt-b show nothing.

**Comment by Ben3eeE** [comment]
@eulogy14 Do you want <kbd>Ctrl-Alt-b</kbd> to beautify? How do you write `{` on your layout if <kbd>Ctrl-Alt-b</kbd> runs the beautify command?

What you can try is to work around this problem using the [public keystroke resolver API](https://github.com/atom/atom-keymap/pull/164). For example to resolve <kbd>Ctrl-Alt-b</kbd> to <kbd>Ctrl-Alt-b</kbd> instead of `{` add something like this to your `init.coffee`

```coffee
atom.keymaps.addKeystrokeResolver ({event}) ->
  if event.code is 'KeyB' and event.altKey and event.ctrlKey and event.type is 'keydown'
    return 'ctrl-alt-b'
```

**Comment by Ben3eeE** [comment]
@flaviolaino Am I reading correct that you have bound `fold-all` and `unfold-all` in your `keymap.cson` and they no longer work after update because the keys now resolve differently? Can you share the contents of your `keymap.cson` file?

**Comment by flaviolaino** [comment]
@Ben3eeE now works for me.

Thanks

**Comment by eulogy14** [comment]
I am using AltGr + B for { and I was using that for the last few years :)

Flavio Laino <notifications@github.com> ezt írta (időpont: 2016. nov. 18.,
P, 12:29):

**Comment by Ben3eeE** [comment]
@eulogy14 What operating system are you on?

**Comment by eulogy14** [comment]
Windows 10, latest build, English display language and Hungarian Qwerty
keyboard

Linus Eriksson <notifications@github.com> ezt írta (időpont: 2016. nov.
21., Hét 7:54):

**Comment by Ben3eeE** [comment]
<kbd>Ctrl-Alt</kbd> and <kbd>AltGr</kbd> is the same thing on Windows. So to be able to use <kbd>AltGr-b</kbd> to write `{` you need to also write it with <kbd>Ctrl-Alt-b</kbd>.

**Comment by eulogy14** [comment]
Yup, but I was using keybind-localization ( or smth called like that)
package which had a hungarian layout, and I was using ctrl-alt-b for
package hotkeys and altgr-key for alternate keys.

Linus Eriksson <notifications@github.com> ezt írta (időpont: 2016. nov.
21., H, 8:19):

**Comment by lee-dohm** [comment]
This appears to be fixed with the recent changes to the Atom keymap system, so I'm going to close it. If anyone is still having problems with this, please let us know and I'll be happy to reopen it.
